apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - rbac.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
  - hpa-pdb.yaml

images:
  - name: hashicorp/http-echo
    newName: hashicorp/http-echo
    newTag: latest    # TeamCity updates this line after every build
